### ISSUE TITLE
package缺少依赖文件

### ISSUE THREAD

**Issue by zybieku** [tggcs/schema-json-vue#1]
很好,页面风格很清晰,也是element的,建议大佬在readme写详细一点,把运行截图,或者把demo往服务器放一下,这样浏览体验好很多,放到github上跑也行.

在使用sass-loader的时候,node-sass要一起依赖,要不然npm install会爆node-sass缺少错误,兄弟可能是全局安装了,另外sass-loader的编译成css时候用的,放到dev里面依赖就可以了
![image](https://user-images.githubusercontent.com/15903330/58164770-09fed380-7cb9-11e9-9340-e2de5093d473.png)

**Comment by tggcs** [comment]
多谢挽尊和提出的宝贵意见～
下班后我瞅瞅，改下～

**Comment by tggcs** [comment]
demo地址是：https://tggcs.github.io/projects/schema-json-vue/index.html
node-sass包的引用加入了，sass-loader位置也调整了～～

**Comment by zybieku** [comment]
大佬牛逼,我拿你的自己瞎改了一下,自己做了一些interger输入校验,max,min,unique判断,等系列细节处理,有时间大佬也可以继续更新 ,把这些功能加上

**Comment by tggcs** [comment]
OK~
